### ISSUE TITLE
TeacupsPro not working

### ISSUE THREAD

**Issue by tanlucvn** [Berehum/teacups#2]
https://pastebin.com/iMc5LmnS

I have install ProtocolLib 4.7.0

**Comment by Berehum** [comment]
Hi! Thanks for reporting this bug and my apologies for the inconvenience. I was able to reproduce the bug by using the latest 1.16.5 version of paper. It seems that paper also uses the adventure library by kyori and that this causes conflicts. In the latest version of TeacupsPro (0.2.1), I will be shading the library to a different package to avoid conflicts. That should fix this bug.

**Comment by Berehum** [comment]
Please [download](https://www.spigotmc.org/resources/teacupspro.99766/) the latest version of TeacupsPro. The bug should be fixed in that version.
